function HdC2 = Cheb2Astop200
%CHEB2ASTOP200 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 14-Jul-2019 19:42:43

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Fstop1 = 50;          % First Stopband Frequency
Fpass1 = 100;         % First Passband Frequency
Fpass2 = 759;         % Second Passband Frequency
Fstop2 = 809;         % Second Stopband Frequency
Astop1 = 200;         % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 200;         % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
HdC2 = design(h, 'cheby2', 'MatchExactly', match);
end

% [EOF]
