function Hdl2 = lowpassEqui2
%LOWPASSEQUI2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 14-Jul-2019 14:45:18

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Fpass = 400;               % Passband Frequency
Fstop = 450;               % Stopband Frequency
Dpass = 0.0057563991496;   % Passband Ripple
Dstop = 3.1622776602e-06;  % Stopband Attenuation
dens  = 20;                % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hdl2 = dfilt.dffir(b);
end

% [EOF]
